### ISSUE TITLE
Improve Server Discovery

### ISSUE THREAD

**Issue by OverlordQ** [spesmilo/electrum-server#146]
Using whois on join is an unscaleable solution. You're already getting the flood disconnects as the server pool grows.

**Comment by ecdsa** [comment]
did you pull the latest code? I pushed a fix 2 days ago

**Comment by OverlordQ** [comment]
It'll fix the timeouts, but using whois is still not really workable for a longer term solution.

**Comment by OverlordQ** [comment]
Further impetus to change server discovery:

    13:05 < niko> could you please not use freenode for peer discovering ?
    13:05 < niko> that's not how we want the network to be used
    13:30 < niko> using freenode for dev / chat whatever is ok, using it by bots to some crypto discovering things is not
